routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/pessoa', 'PessoaC');
Route::resource('/endereco', 'EnderecoC');
Route::resource('/filme', 'FilmeC');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/cromg.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Teste CROMG">
    <meta name="author" content="Ederson Carmo">
    <link rel="icon" href="../../../../favicon.ico">

    <title>CROMG</title>

  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="{!! asset('css/bootstrap.min.css') !!}" rel="stylesheet">
    <link href="{{ asset('css/dataTables.bootstrap4.css') }}" rel="stylesheet">
 <link href="{{ asset('css/select2.min.css') }}" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="{!! asset('css/carousel.css') !!}" rel="stylesheet">
  <link rel="stylesheet" href="{{ asset('css/toastr.min.css') }}">

  </head>
  <body>

    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{{ url('/home') }}">{{ config('app.name') }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {{ isset($rota['rota'])? $rota['rota']=='pessoa'?'active':'':''}}">
              <a class="nav-link" href="{{ route('pessoa.index') }}">Pessoas <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {{ isset($rota['rota'])? $rota['rota']=='filme'?'active':'':''}}">
              <a class="nav-link" href="{{ route('filme.index') }}">Filmes</a>
            </li>
            <li class="nav-item {{ isset($rota['rota'])? $rota['rota']=='endereco'?'active':'':''}}">
              <a class="nav-link" href="{{ route('endereco.index') }}">Endereços</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>


            <main class="py-4">
                @yield('content')
            </main>

                  <!-- FOOTER -->
                  <footer class="container">
                    <p class="float-right"><a href="#">Topo</a></p>
                    <p>2018 Ederson Carmo, Projeto CROMG.</p>
                  </footer>

    <!-- Bootstrap core JavaScript
    ==================================================
  -->
<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('js/jquery.mask.min.js') }}"></script>

  <script type="text/javascript" src="{{ asset('js/jquery.dataTables.js') }}" class="view-script"></script>
<script type="text/javascript" src="{{ asset('js/dataTables.bootstrap4.js') }}" class="view-script"></script>
<script type="text/javascript" src="{{ asset('js/datatables.js') }}" class="view-script"></script>

<script src="{{ asset('vendors/select2.min.js') }}"></script>

    <!-- Placed at the end of the document so the pages load faster -->
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="{!! asset('js/popper.min.js') !!}"></script>
    <script src="{!! asset('js/bootstrap.min.js') !!}"></script>

<script type="text/javascript" src="{{ asset('vendors/toastr.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/toastr.js') }}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{!! asset('js/holder.min.js') !!}"></script>
    <script src="{!! asset('js/cromg.js') !!}"></script>
  </body>
</html>